export const colors = {
	COLOR_VALUE_PRIMARY: '#232d37',
	COLOR_BACKGROUND: '#edf2f5',
	COLOR_VALUE: '#232f3f',
	COLOR_ORANGE: '#f37022',
	COLOR_BORDER: '#d9dde0',
	COLOR_BUTTON_HEADER: '#0f1a29',
	COLOR_AVAILABLE: '#2bc95f',
	COLOR_PLACEHOLDER_TEXT: '#cdcdcd',
	COLOR_BORDER_BUTTON: 'white'
};
