import React from 'react';

export const valueString = {
  VALUE_HOME_PAGE_INTERNET_REPORT: 'Sitting',
  VALUE_DETAILES_BED_ACTIVE_STATUSE: 'Active',
  VALUE_MESSAGE_EXIT_ATTENDANCE_SUCCESS: 'You exit from Attendance',
  VALUE_INTITY_DETAILES: 'Detailes Bed',
  VALUE_UPDATE_SUCCESS: 'Services Updated Successfull',
  VALUE_UPDATE_SUCCESS: 'Intities Updated Successfull',
  VALUE_ENTITY: 'List of my Beds',
  VALUE_ENTITY_MENU: 'My Beds',
  VALUE_DETAILES_BED_ALL_SERVICES: 'Update Services :',
  VALUE_BEDS: 'beds',
  VALUE_DETAILES_BED_TITLE: 'Title :',
  VALUE_DETAILES_BED_SERVICE: 'Selected Services:',
  VALUE_DETAILES_BED_DESCRIPTION: 'Description :',
  VALUE_DETAILES_BED_AUTH_TYPE: 'Auth Type :',
  VALUE_DETAILES_BED_ITEM_COUNT: 'Services Count :',
  VALUE_SERVICES: 'Services',
  VALUE_HOME_PAGE_IN_PERSON_REPORT: 'Request list',
  VALUE_SERVICES_LIST: 'Services List',
  VALUE_HOME_PAGE_NEED_SHOP: 'نیاز های فروشگاه',
  VALUE_HOME_PAGE_IMPORT_PRODUCT: 'Sitting',
  VALUE_HOME_PAGE_COVERAGE: 'شعاع تحت پوشش :',
  VALUE_HOME_PAGE_KM: 'کیلومتر',
  VALUE_HOME_PAGE_VARIETY_OF_GOODS: 'تنوع کالا :',
  VALUE_HOME_PAGE_NUMBER: 'عدد',
  VALUE_MESSAGE_SUCCESS_UPDATE_PRODUCT:
    'اطلاعات محصول با موفقیت به روزرسانی شد',
  VALUE_MESSAGE_CONFIRM: 'OK',
  VALUE_MESSAGE_ERROR_UPDATE_PRODUCT:
    'اطلاعات محصول با موفقیت به روز رسانی نشد',
  VALUE_MESSAGE_SUCCESS_CREATE_PRODUCT: 'محصول با موفقیت اضافه شد',
  VALUE_MESSAGE_ERROR_CREATE_PRODUCT: 'محصول با موفقیت اضافه نشد',
  VALUE_MESSAGE_EXIT_FROM_ACCOUNT: 'Are you sure you want to exit the App?',
  VALUE_MESSAGE_EXIT_FROM_ATTENDANCE:
    'Are you sure you want to exit this Attendance?',
  VALUE_MESSAGE_YES: 'Yes',
  VALUE_MESSAGE_NO: 'No',
  VALUE_LOGIN_PAGE_REMEMBER_ME: 'مرا به خاطر بسپار',
  VALUE_MAIN_MENU_EXIT: 'Exit',
  VALUE_MAIN_MENU_SUPPORT: 'Support',
  VALUE_PHONE_SUPPORT_NUMBER: '(+98)118',
  VALUE_MAIN_MENU_HELP: 'راهنما',
  VALUE_MAIN_MENU_HOME: 'Home',
  VALUE_TITLE_SELECTED_NEW_ENTITY: 'Add bed:',
  VALUE_LOGIN_PAGE_PLACEHOLDER_PASSWORD: 'password',
  VALUE_LOGIN_PAGE_PLACEHOLDER_USERNAME: 'username',
  VALUE_LOGIN_PAGE_PLACEHOLDER_EMAIL: 'email',
  VALUE_LOGIN_PAGE_PLACEHOLDER_VERIFY_CODE: 'verify code',
  VALUE_LOGIN_PAGE_PLACEHOLDER_NEW_PASSWORD: 'enter new password',
  VALUE_LOGIN_PAGE_PLACEHOLDER_NEW_PASSWORD_AGAIN: 'enter new password again',
  VALUE_LOGIN_PAGE_CHANGE_PASSWORD: 'change password',
  VALUE_LOGIN_PAGE_LOGIN: 'Login',
  VALUE_LOGIN_PAGE_SEND_CODE: 'send code',
  VALUE_CONFIRM: 'OK',
  VALUE_UPDATING: 'Updating Requests',
  VALUE_UPDATING_ENTITY: 'Submit',
  VALUE_MAIN_MENU_LOGOUT: 'Logout',
  VALUE_TITLE_EXIT_FROM_ACCOUNT: 'Exit from App',
  VALUE_GREETING_MESSAGE: 'تبریک',
  VALUE_SEARCH: 'جستجو',
  VALUE_LOGIN_PAGE_ERROR: 'Enter your username and password',
  VALUE_LOGIN_PAGE_ERROR_EMAIL: 'Enter your email',
  VALUE_LOGIN_PAGE_ERROR_VERIFY: 'Enter Verify Code',
  VALUE_LOGIN_PAGE_ERROR_INVALID: 'Enter your username and password correctly',
  VALUE_NEED_PAGE_PLACEHOLDER_BARE_CODE_READER:
    'بار کد محصول مورد نظر خود را وارد نمایید',
  VALUE_NEED_PAGE_DETAILS_NEEDS_SHOP: 'جزییات نیاز فروشگاه شما',
  VALUE_NEED_PAGE_NEED_WEEK: 'نیاز های هفته :',
  VALUE_NEED_PAGE_NEED_MONTH: 'نیاز های ماه آینده:',
  VALUE_NEED_PAGE_DETAILS_NEEDS_PRODUCT: 'جزییات فروش محصول ',
  VALUE_NEED_PAGE_NEED_TODAY: 'نیاز های امروز:',
  VALUE_NEED_PAGE_NUMBER: 'عدد',
  VALUE_NEED_PAGE_SALE_LAST_MONTH: 'فروش ماه گذشته:',
  VALUE_NEED_PAGE_ERROR_NO_REPORT: 'هیچ گزارشی از این محصول ثبت نشده است',
  VALUE_NEED_PAGE_ERROR_NO_BAR_CODE: 'بارکد نمی تواند خالی باشد',
  VALUE_NEED_PAGE_TITLE:
    'تعداد فروش در یک ماه گذشته و پیشنهاد خرید برای آینده را مشاهده نمایید.',
  VALUE_NEED_PAGE_SUB_TITLE:
    ' این ویژگی به شما کمک می کند تا هنگام تامین کالای دقیق و به اندازه سفارش دهید .',
  VALUE_HANDY: 'دستی',
  VALUE_INTERNET_PAGE_MESSAGE_NO_ORDER: 'هیچ سفارشی ثبت نشده است',
  VALUE_INTERNET_PAGE_STATE_NEW: ' سفارشات جدید',
  VALUE_INTERNET_PAGE_STATE_WAITING: ' منتظر تایید مشتری',
  VALUE_INTERNET_PAGE_STATE_PAKE: 'تحویل به پیک',
  VALUE_INTERNET_PAGE_STATE_DELIVER: ' تحویل به مشتری',
  VALUE_INTERNET_PAGE_TITLE_TABLE_NUMBER: 'شماره',
  VALUE_INTERNET_PAGE_TITLE_TABLE_CUSTOMER: 'مشتری',
  VALUE_INTERNET_PAGE_TITLE_TABLE_DATE: 'description',
  VALUE_INTERNET_PAGE_TITLE_TABLE_PRICE: 'price',
  VALUE_INTERNET_PAGE_TITLE_TABLE_MONEY: 'user Identify',
  VALUE_INTERNET_PAGE_TITLE_TABLE_STATUS: 'status',
  VALUE_IN_PERSON_PAGE_SELLER: 'name Item',
  VALUE_IN_PERSON_PAGE_CODE: 'request Identify',
  VALUE_TOMAN: 'تومان',
  VALUE_REAL: 'ریال',
  VALUE_SPLASH_PAGE_NO_INTERNET: 'اتصال اینترنت خود را چک کنید',
  VALUE_UPDATE: 'به روز رسانی',
  VALUE_DETAIL_INTERNET_PAGE_INFORMATION_PAKE: 'اطلاعات پیک',
  VALUE_DETAIL_INTERNET_PAGE_SELECT_PAKE: 'انتخاب پیک:',
  VALUE_DETAIL_INTERNET_PAGE_SELECTION: 'پیک را انتخاب نمایید',
  VALUE_DETAIL_INTERNET_PAGE_DELIVERY_PAKE: 'تحویل به پیک',
  VALUE_DETAIL_INTERNET_PAGE_SELECT_PRODUCT: 'انتخاب کالای جایگزین',
  VALUE_DETAIL_INTERNET_PAGE_HANDY: 'دستی',
  VALUE_DETAIL_INTERNET_PAGE_BAR_CODE: 'بار کد خوان',
  VALUE_DETAIL_INTERNET_PAGE_UNAVAILABLE: ' ناموجود',
  VALUE_DETAIL_INTERNET_PAGE_AVAILABLE: 'موجود',
  VALUE_DETAIL_INTERNET_PAGE_READY: 'تایید آماده سازی سفارش',
  VALUE_DETAIL_INTERNET_PAGE_DELIVERY_TO_CUSTOMER: 'تحویل به مشتری',
  VALUE_DETAIL_INTERNET_PAGE_DELIVERED: 'سفارش به مشتری تحویل داده شده است',
  VALUE_DETAIL_INTERNET_PAGE_ORDER_TITLE: 'مشخصات سفارش',
  VALUE_DETAIL_INTERNET_PAGE_TIME_DATE: 'تاریخ :',
  VALUE_DETAIL_INTERNET_PAGE_ORDER_NUMBER: 'شماره سفارش :',
  VALUE_DETAIL_INTERNET_PAGE_MONEY: 'مبلغ سفارش:',
  VALUE_DETAIL_INTERNET_PAGE_CUSTOMER_NAME: 'نام مشتری:',
  VALUE_DETAIL_INTERNET_PAGE_ADDRESS: 'آدرس:',
  VALUE_DETAIL_INTERNET_PAGE_CUSTOMER_NOTE: 'یادداشت مشتری :',
  VALUE_DETAIL_INTERNET_PAGE_ORDER_LIST: 'ليست سفارش كالا',
  VALUE_DETAIL_INTERNET_PAGE_ORDER_ITEMS: 'مشاهده لیست اقلام سفارش',
  VALUE_DETAIL_INTERNET_PAGE_FINANCIAL_INFORMATION: 'اطلاعات مالی',
  VALUE_DETAIL_INTERNET_PAGE_TOTAL_MONEY: 'مبلغ کل سفارش:',
  VALUE_DETAIL_INTERNET_PAGE_USE_CREDIT: 'مقدار استفاده از اعتبار :',
  VALUE_DETAIL_INTERNET_PAGE_DISCOUNT_SHOP: 'تخفیفات فروشگاه:',
  VALUE_DETAIL_INTERNET_PAGE_DISCOUNT_SHOP_PERCENT: 'درصد',
  VALUE_DETAIL_INTERNET_PAGE_PAYMENT_TYPE: 'نوع پرداخت :',
  VALUE_DETAIL_INTERNET_PAGE_RECEIVE: 'مبلغ دریافتی از مشتری:',
  VALUE_DETAIL_INTERNET_PAGE_CASH: 'نقدی',
  VALUE_SCANNER_PAGE_BARCODE_READER: 'QR Code Reader',
  VALUE_SCANNER_PAGE_RETURN: ' Return To Previous Page ',
  VALUE_IMPORT_PRODUCT_EMPTY_FIELD: 'نام و یا بار کد محصول را وارد نمایید',
  VALUE_IMPORT_PRODUCT_EMPTY_BAR_CODE: 'فیلد بارکد نمی تواند خالی باشد',
  VALUE_IMPORT_PRODUCT_NOT_FIND_PRODUCT: 'خطا در یافتن محصول',
  VALUE_IMPORT_PRODUCT_ADD_PRODUCT: 'اضافه کردن محصول',
  VALUE_IMPORT_PRODUCT_NOT_FIND_PRODUCT_WITH_BAR_CODE:
    'هیچ محصولی با این بار کد یافت نشد',
  VALUE_SEARCH_PRODUCT: 'نام محصول یا بار کد محصول را وارد نمایید',
  VALUE_IMPORT_PRODUCT_INFORMATION_TITLE: ' مشخصات کالا',
  VALUE_IMPORT_PRODUCT_BAR_CODE_TITLE: 'بارکد',
  VALUE_IMPORT_PRODUCT_PRODUCT_NAME: 'نام کالا :',
  VALUE_IMPORT_PRODUCT_IN_PERSON_PRICE: 'قیمت فروش حضوری (ریال)',
  VALUE_IMPORT_PRODUCT_IN_PERSON_PERCENT: 'تخفیف(درصد)',
  VALUE_IMPORT_PRODUCT_FIX_PERCENT: 'تخفیف (مبلغ به ریال)',
  VALUE_IMPORT_PRODUCT_BUY_PRICE: ' قیمت خرید(ریال)',
  VALUE_IMPORT_PRODUCT_CATEGORIES: 'دسته بندی',
  VALUE_IMPORT_PRODUCT_SELECT_CATEGORIES:
    'یکی از دسته بندی ها را انتخاب نمایید',
  VALUE_IMPORT_PRODUCT_SHOW_IN_SITE: 'نمایش در سایت',
  VALUE_IMPORT_PRODUCT_CANCEL: 'لغو',
  VALUE_IMPORT_PRODUCT_INTERNET_PRICE: ' قیمت فروش اینترنتی (ریال)',
  VALUE_IMPORT_PRODUCT_INTERNET_PERCENT: ' درصد تخفیف فروش اینترنتی',
  VALUE_IMPORT_PRODUCT_SELECT_METHOD_TO_SEARCH:
    'به کمک یکی از روش های زیر محصول را جستحو کنید :',
  VALUE_IMPORT_PRODUCT_ERROR_NAME_FIELD: 'فیلد نام نمی تواند خالی باشد\n',
  VALUE_IMPORT_PRODUCT_ERROR_IN_PERSON_FIELD:
    'فیلد قیمت حضوری نمی تواند خالی باشد\n',
  VALUE_IMPORT_PRODUCT_ERROR_INTERNET_FIELD:
    'فیلد قیمت اینترنتی نمی تواند خالی باشد\n',
  VALUE_IMPORT_PRODUCT_IN_PERSOEN_PERCENT_FIELD:
    'مقدار تخیفیف فروش حضوری نمی تواند بیشتر از ۱۰۰باشد\n',
  VALUE_IMPORT_PRODUCT_IN_INTERNET_PERCENT_FIELD:
    'مقدار تخیفیف ثابت نمی تواند بیشتر از ۱۰۰باشد\n',
  VALUE_IMPORT_PRODUCT_HANDY: 'دستی',
  VALUE_IMPORT_PRODUCT_BARCODE_READ: 'QR Code Reader',
  VALUE_DETAILS_PRODUCT: 'جزئیات محصول',
  VALUE_DETAILS_PRODUCT_SET_QUANTITY: 'به روزرسانی  اطلاعات و موجودی محصول',
  VALUE_UPDATE_QUANTITY: 'به روز رسانی موجودی ',
  VALUE_SET_QUANTITY_UPDATE_SUCCESS: 'موجودی محصول با موفقیت به بروز رسانی شد',
  VALUE_SET_QUANTITY_UPDATE_FAIL: 'موجودی محصول باموفقیت به روز رسانی نشد',
  VALUE_SET_QUANTITY_DO_NOT_EMPTY: 'مقدار موجودی نباید خالی باشد',
  VALUE_SET_QUANTITY_PLACEHOLDER_PRODUCT_QTY:
    'تعداد موجودی محصول را وارد نمایید',
  VALUE_DETAILS_PRODUCT_SET_QUANTITY_NEW: 'اضافه و به روزرسانی موجودی محصول',
  VALUE_MOMENT_REPORT_DAILY: 'فروش روز جاری :',
  VALUE_MOMENT_REPORT_MONTHLY: 'فروش ماه جاری :',
  VALUE_MESSAGE_NO_FOUND_PRODUCT: 'هیچ گزارشی از این محصول ثبت نشده است ',
  VALUE_DETAILS_NEED_MAIN_TITLE: 'جزئیات نیاز های فروشگاه',
  VALUE_DETAILS_NEED_PAGE_MOUNT: 'نیاز های ماه آینده :',
  VALUE_DETAILS_NEED_PAGE_WEEK: 'نیاز هفته :',
  VALUE_DETAILS_NEED_PAGE_DAY: 'نیاز های امروز :',
  VALUE_DETAILS_NEED_PAGE_TITLE: 'جزییات نیاز فروشگاه شما',
  VALUE_DETAILS_NEED_PAGE_LAST_MONTH: ' فروش ماه گذشته :',
  VALUE_DETAILS_NEED_PAGE_SUB_TITLE: 'جزییات فروش محصول',
};
